# Generated by Django 3.2.10 on 2021-12-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_data',
            new_name='order_date',
        ),
    ]
